Repository DioxusLabs/components, pull requests merged in 2025-06, with the labels that each got.

#39 Fix keyboard navigation in the radio component
  preview/assets/.DS_Store
  primitives/src/radio_group.rs
Labels: bug

#40 Remove all mutable signals from props and extend attributes where possible
  preview/src/components/alert_dialog/mod.rs
  preview/src/components/alert_dialog/style.css
  preview/src/components/dialog/docs.md
  preview/src/components/dialog/mod.rs
  preview/src/components/dialog/style.css
  preview/src/components/mod.rs
  preview/src/components/switch/mod.rs
  primitives/src/alert_dialog.rs
  primitives/src/calendar.rs
  primitives/src/checkbox.rs
  primitives/src/collapsible.rs
  primitives/src/context_menu.rs
  primitives/src/dialog.rs
  primitives/src/dropdown_menu.rs
  primitives/src/hover_card.rs
  primitives/src/lib.rs
  primitives/src/progress.rs
  primitives/src/radio_group.rs
  primitives/src/select.rs
  primitives/src/separator.rs
  primitives/src/slider.rs
  primitives/src/switch.rs
  primitives/src/tabs.rs
  primitives/src/toast.rs
  primitives/src/toggle.rs
  primitives/src/toggle_group.rs
  primitives/src/tooltip.rs
Labels: breaking

#43 Calendar keyboard navigation, focus radiogroup and focus indicator for accordion
  preview/src/components/accordion/style.css
  primitives/src/calendar.rs
  primitives/src/radio_group.rs
Labels: bug, accessability

#22 Focusout for Dropdown, Menubar and ContextMenu
  preview/src/components/context_menu/mod.rs
  preview/src/components/context_menu/style.css
  preview/src/components/dropdown_menu/style.css
  preview/src/components/menubar/mod.rs
  preview/src/components/menubar/style.css
  primitives/src/context_menu.rs
  primitives/src/dropdown_menu.rs
  primitives/src/menubar.rs
Labels: bug, accessability, styling

#48 Add and pass an automated aria playwright CI
  .github/workflows/main.yml
  .github/workflows/playwright.yml
  .gitignore
  playwright/package-lock.json
  playwright/package.json
  playwright/playwright.config.ts
  playwright/preview.spec.ts
  preview/index.html
  preview/src/components/avatar/mod.rs
  preview/src/components/checkbox/mod.rs
  preview/src/components/hover_card/mod.rs
  preview/src/components/progress/mod.rs
  preview/src/components/scroll_area/mod.rs
  preview/src/components/select/mod.rs
  preview/src/components/slider/mod.rs
  preview/src/components/switch/mod.rs
  preview/src/components/tabs/docs.md
  preview/src/components/tabs/mod.rs
  preview/src/main.rs
  primitives/src/calendar.rs
  primitives/src/context_menu.rs
  primitives/src/dropdown_menu.rs
  primitives/src/hover_card.rs
  primitives/src/select.rs
  primitives/src/slider.rs
  primitives/src/tabs.rs
Labels: accessability

#51 Add light/dark mode toggle to the preview
  preview/assets/main.css
  preview/assets/theme.css
  preview/src/components/alert_dialog/style.css
  preview/src/components/calendar/style.css
  preview/src/components/context_menu/style.css
  preview/src/components/dialog/style.css
  preview/src/components/dropdown_menu/style.css
  preview/src/components/hover_card/style.css
  preview/src/components/menubar/style.css
  preview/src/components/radio_group/style.css
  preview/src/components/select/style.css
  preview/src/components/switch/style.css
  preview/src/components/tabs/style.css
  preview/src/components/toast/style.css
  preview/src/components/toolbar/style.css
  preview/src/main.rs
Labels: styling, preview

#59 Stylable select component
  README.md
  playwright/preview.spec.ts
  preview/assets/main.css
  preview/src/components/collapsible/docs.md
  preview/src/components/collapsible/mod.rs
  preview/src/components/collapsible/style.css
  preview/src/components/input/docs.md
  preview/src/components/input/mod.rs
  preview/src/components/input/style.css
  preview/src/components/label/docs.md
  preview/src/components/label/mod.rs
  preview/src/components/label/style.css
  preview/src/components/mod.rs
  preview/src/components/select/mod.rs
  preview/src/components/select/style.css
  preview/src/components/toggle/docs.md
  preview/src/components/toggle/mod.rs
  preview/src/components/toggle/style.css
  preview/src/components/toggle_group/style.css
  preview/src/main.rs
  primitives/src/collapsible.rs
  primitives/src/hover_card.rs
  primitives/src/select.rs
Labels: enhancement

#62 Fix mobile interactions in menus and prevent mouse interactions outside of open context menu
  preview/Cargo.toml
  preview/build.rs
  primitives/Cargo.toml
  primitives/src/alert_dialog.rs
  primitives/src/context_menu.rs
  primitives/src/dialog.rs
  primitives/src/dropdown_menu.rs
  primitives/src/lib.rs
  primitives/src/menubar.rs
  primitives/src/navbar.rs
  primitives/src/popover.rs
  primitives/src/radio_group.rs
  primitives/src/select.rs
  primitives/src/slider.rs
  primitives/src/tabs.rs
  primitives/src/toast.rs
  primitives/src/toggle_group.rs
  primitives/src/tooltip.rs
Labels: bug, mobile

#64 Fix toast safari
  preview/assets/theme.css
  preview/src/components/toast/style.css
  primitives/src/toast.rs
Labels: bug, styling, safari

#65 Pull out button styles
  preview/assets/theme.css
  preview/src/components/alert_dialog/mod.rs
  preview/src/components/alert_dialog/style.css
  preview/src/components/button/docs.md
  preview/src/components/button/mod.rs
  preview/src/components/button/style.css
  preview/src/components/dialog/mod.rs
  preview/src/components/dialog/style.css
  preview/src/components/input/docs.md
  preview/src/components/mod.rs
  preview/src/components/popover/mod.rs
  preview/src/components/popover/style.css
  preview/src/components/toast/mod.rs
  preview/src/components/toast/style.css
  preview/src/components/tooltip/style.css
Labels: styling

#71 Fix transitioning in components
  Cargo.lock
  preview/Cargo.toml
  preview/assets/hero.css
  preview/assets/main.css
  preview/src/components/accordion/style.css
  preview/src/components/alert_dialog/style.css
  preview/src/components/avatar/style.css
  preview/src/components/button/style.css
  preview/src/components/collapsible/style.css
  preview/src/components/context_menu/style.css
  preview/src/components/dialog/style.css
  preview/src/components/dropdown_menu/style.css
  preview/src/components/hover_card/style.css
  preview/src/components/menubar/style.css
  preview/src/components/navbar/style.css
  preview/src/components/popover/style.css
  preview/src/components/select/style.css
  preview/src/main.rs
  primitives/src/accordion.rs
  primitives/src/alert_dialog.rs
  primitives/src/context_menu.rs
  primitives/src/dialog.rs
  primitives/src/dropdown_menu.rs
  primitives/src/hover_card.rs
  primitives/src/lib.rs
  primitives/src/menubar.rs
  primitives/src/navbar.rs
  primitives/src/popover.rs
  primitives/src/select.rs
  primitives/src/tooltip.rs
Labels: bug, styling
